// <auto-generated />
using System;
using CasaDoCodigo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Capitulo05Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("CasaDoCodigo.Models.Cliente", b =>
                {
                    b.Property<long?>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OficinaModels.Atendimentos.Atendimento", b =>
                {
                    b.Property<long?>("AtendimentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClienteID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraChegada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraPrometida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Veiculo")
                        .HasColumnType("TEXT");

                    b.HasKey("AtendimentoID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("OficinaModels.Cadastros.Servico", b =>
                {
                    b.Property<long?>("ServicoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("ServicoID");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("OficinaModels.Atendimentos.Atendimento", b =>
                {
                    b.HasOne("CasaDoCodigo.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID");
                });
#pragma warning restore 612, 618
        }
    }
}
