// <auto-generated />
using System;
using CCFoodsServer.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CCFoodsServer.Migrations
{
    [DbContext(typeof(CCFoodsContext))]
    partial class CCFoodsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CCFoodsServer.Models.ConfiguracaoDispositivo", b =>
                {
                    b.Property<long?>("ConfiguracaoDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMail");

                    b.HasKey("ConfiguracaoDispositivoId");

                    b.ToTable("ConfiguracoesDispositivos");
                });

            modelBuilder.Entity("CCFoodsServer.Models.Garcom", b =>
                {
                    b.Property<string>("GarcomId");

                    b.Property<long?>("DispositivoId");

                    b.Property<long?>("EntityId");

                    b.Property<byte[]>("Foto");

                    b.Property<string>("Nome");

                    b.Property<int>("OperacaoSincronismo");

                    b.Property<string>("Sobrenome");

                    b.HasKey("GarcomId");

                    b.ToTable("Garcons");
                });
#pragma warning restore 612, 618
        }
    }
}
