// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerAPI.Persistencia;

namespace ServerAPI.Migrations
{
    [DbContext(typeof(CCFoodsContext))]
    [Migration("20200713204230_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServerAPI.Models.ConfiguracaoDispositivo", b =>
                {
                    b.Property<long?>("ConfiguracaoDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfiguracaoDispositivoId");

                    b.ToTable("ConfiguracoesDispositivos");
                });

            modelBuilder.Entity("ServerAPI.Models.Garcom", b =>
                {
                    b.Property<string>("GarcomId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("DispositivoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperacaoSincronismo")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GarcomId");

                    b.ToTable("Garcons");
                });
#pragma warning restore 612, 618
        }
    }
}
